# Generated by Django 3.0.2 on 2020-01-16 06:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('detail_board', '0003_auto_20200116_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='family_board',
            name='scrap',
            field=models.ManyToManyField(blank=True, related_name='user_scrap', to=settings.AUTH_USER_MODEL),
        ),
    ]
