# Generated by Django 3.0.2 on 2020-01-16 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('detail_board', '0004_family_board_scrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='army_board',
            name='catagory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='army_board',
            name='scrap',
            field=models.ManyToManyField(blank=True, related_name='army_scrap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business_board',
            name='catagory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business_board',
            name='scrap',
            field=models.ManyToManyField(blank=True, related_name='business_scrap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='children_board',
            name='catagory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='children_board',
            name='scrap',
            field=models.ManyToManyField(blank=True, related_name='children_scrap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client_board',
            name='catagory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client_board',
            name='scrap',
            field=models.ManyToManyField(blank=True, related_name='client_scrap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crime_board',
            name='catagory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crime_board',
            name='scrap',
            field=models.ManyToManyField(blank=True, related_name='crime_scrap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eco_board',
            name='catagory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eco_board',
            name='scrap',
            field=models.ManyToManyField(blank=True, related_name='eco_scrap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estate_board',
            name='catagory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estate_board',
            name='scrap',
            field=models.ManyToManyField(blank=True, related_name='estate_scrap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='family_board',
            name='catagory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financial_board',
            name='catagory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financial_board',
            name='scrap',
            field=models.ManyToManyField(blank=True, related_name='financial_scrap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='government_board',
            name='catagory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='government_board',
            name='scrap',
            field=models.ManyToManyField(blank=True, related_name='government_scrap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='information_board',
            name='catagory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='information_board',
            name='scrap',
            field=models.ManyToManyField(blank=True, related_name='information_scrap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labor_board',
            name='catagory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labor_board',
            name='scrap',
            field=models.ManyToManyField(blank=True, related_name='labor_scrap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lawsuit_board',
            name='catagory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lawsuit_board',
            name='scrap',
            field=models.ManyToManyField(blank=True, related_name='lawsuit_scrap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leisure_board',
            name='catagory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leisure_board',
            name='scrap',
            field=models.ManyToManyField(blank=True, related_name='leisure_scrap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='startup_board',
            name='catagory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='startup_board',
            name='scrap',
            field=models.ManyToManyField(blank=True, related_name='startup_scrap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trade_board',
            name='catagory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trade_board',
            name='scrap',
            field=models.ManyToManyField(blank=True, related_name='trade_scrap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traffic_board',
            name='catagory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='traffic_board',
            name='scrap',
            field=models.ManyToManyField(blank=True, related_name='traffic_scrap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='welfare_board',
            name='catagory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='welfare_board',
            name='scrap',
            field=models.ManyToManyField(blank=True, related_name='welfare_scrap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='family_board',
            name='scrap',
            field=models.ManyToManyField(blank=True, related_name='family_scrap', to=settings.AUTH_USER_MODEL),
        ),
    ]
