# Generated by Django 2.2.7 on 2020-01-17 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LawBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(null=True, verbose_name='Date published')),
                ('scrap_id', models.IntegerField(null=True)),
                ('catagory', models.CharField(max_length=100, null=True)),
                ('body', models.TextField()),
                ('scrap', models.ManyToManyField(blank=True, related_name='LawBoard_scrap', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(null=True, verbose_name='Date published')),
                ('body', models.TextField()),
                ('law', models.CharField(default='SOME STRING', max_length=100)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MB_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField()),
                ('comment_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mbcomment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawboard.MeetingBoard')),
            ],
        ),
        migrations.CreateModel(
            name='LB_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField()),
                ('comment_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lbcomment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawboard.LawBoard')),
            ],
        ),
    ]
