# Generated by Django 3.0.2 on 2020-01-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawboard', '0003_mb_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingboard',
            name='law',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
